spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/homeauto
    username: root
    password: root
  sql:
    init:
      platform: mysql
      mode: always
